apiVersion: apps/v1
kind: Deployment
metadata:
  name: wm-employer-service
  labels:
    app: wm-employer-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wm-employer-service
  template:
    metadata:
      labels:
        app: wm-employer-service
    spec:
      containers:
        - name: wm-employer-service
          image:
          ports:
            - containerPort: 8080