apiVersion: v1
kind: Service
metadata:
  name: wm-employer-service
  labels:
    app: wm-employer-service
spec:
  type: LoadBalancer
  selector:
    app: wm-employer-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080